version: '3.8'
services:
  api:
    container_name: api
    expose:
      - 3000
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    - .:/usr/src/app/node_modules/

    command: npm run dev

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
 pgdata: